ALTER TABLE files ALTER COLUMN folder_id DROP NOT NULL;
ALTER TABLE files DROP CONSTRAINT fk_files_folder;
ALTER TABLE files ADD CONSTRAINT fk_files_folder FOREIGN KEY (folder_id) REFERENCES folders(id) ON DELETE SET NULL;
